package config

const (
	//下面8个参数要从环境变量中读取
	REDIS_HOST               = "REDIS_HOST"
	REDIS_MAXIDLE            = "REDIS_MAXIDLE"
	REDIS_MAXACTIVE          = "REDIS_MAXACTIVE"
	SERVER_PORT              = "SERVER_PORT"
	USER_MYSQL_DATABASE_NAME = "USER_MYSQL_DATABASE_NAME"
	USER_MYSQL_HOST          = "USER_MYSQL_HOST"
	USER_MYSQL_USER          = "USER_MYSQL_USER"
	USER_MYSQL_PASSWORD      = "USER_MYSQL_PASSWORD"

	REDIS_MAXIDLE_DEFAULT            = 10
	REDIS_MAXACTIVE_DEFAULT          = 10
	REDIS_HOST_DEFAULT               = "localhost:6379"
	SERVER_PORT_DEFAULT              = 13331
	USER_MYSQL_DATABASE_NAME_DEFAULT = "user"
	USER_MYSQL_HOST_DEFAULT          = "localhost:33066"
	USER_MYSQL_USER_DEFAULT          = "root"
	USER_MYSQL_PASSWORD_DEFAULT      = "123456"
)
